import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {defaults} from '../core.mjs';
import {createStorage,validateDirectory,storageEnvironment} from '../storage.mjs';
import {parseProgress} from '../progress.mjs';
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'mineru-storage-test-'));const state={settings:{...defaults,workRoot:path.join(root,'work'),modelRoot:path.join(root,'models'),outputRoot:path.join(root,'results')},tasks:[]};let busy=false;const config={'models-dir':{}};const create=()=>createStorage({dataRoot:path.join(root,'data'),state,save:()=>{},busy:()=>busy,modelConfig:()=>config});const manager=create();t.after(()=>{assert.ok(path.basename(root).startsWith('mineru-storage-test-'));fs.rmSync(root,{recursive:true,force:true});});return {root,state,manager,config,create,setBusy:v=>busy=v};}
function put(p,text='fixture'){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,text);return p;}
function clean(manager,plan,items=plan.items.filter(i=>i.safe)){return manager.clean({planId:plan.planId,ids:items.map(i=>i.id),confirm:'DELETE_REBUILDABLE_RESOURCES'});}
test('all substantial child caches and temporary paths use selected directories',t=>{const {state,manager}=fixture(t);const r=manager.prepare(state.settings,'download');const env=storageEnvironment(state.settings,r.temp);for(const key of ['TEMP','TMP','TMPDIR'])assert.equal(env[key],r.temp);for(const key of ['HF_HOME','HF_HUB_CACHE','HUGGINGFACE_HUB_CACHE','HF_XET_CACHE','MODELSCOPE_CACHE'])assert.ok(env[key].startsWith(state.settings.modelRoot+path.sep));for(const key of ['PIP_CACHE_DIR','XDG_CACHE_HOME','TORCH_HOME'])assert.ok(env[key].startsWith(state.settings.workRoot+path.sep));});
test('clean known partials and temps; preserve model weights, originals, successful images, edits and unknown files',t=>{
 const {root,state,manager,config}=fixture(t);const resources=manager.prepare(state.settings,'download');put(path.join(resources.temp,'staging.bin'));const partial=put(path.join(state.settings.modelRoot,'huggingface/hub/models--x/blobs/a.incomplete'));const weight=put(path.join(state.settings.modelRoot,'huggingface/hub/models--x/blobs/weight'));config['models-dir'].pipeline=path.join(state.settings.modelRoot,'huggingface/hub/models--x/snapshots/live');fs.mkdirSync(config['models-dir'].pipeline,{recursive:true});const original=put(path.join(root,'original.pdf'));const md=put(path.join(root,'results/good/paper.md'));const image=put(path.join(root,'results/good/images/figure.png'));const edited=put(md+'.edited.md');const unknown=put(path.join(state.settings.workRoot,'unrelated.tmp'));state.tasks.push({source:original,markdown:md,edited,status:'completed',outputDir:path.dirname(md)});
 const plan=manager.scan();assert.ok(plan.items.some(i=>i.path===partial));assert.equal(plan.items.length,2);const result=clean(manager,plan);assert.ok(result.bytes>0);for(const file of [weight,original,md,image,edited,unknown])assert.ok(fs.existsSync(file),file);assert.ok(!fs.existsSync(partial));assert.ok(!fs.existsSync(resources.temp));assert.equal(manager.scan().items.length,0);
});
test('failed outputs require explicit selection; protected source inside is never removed',t=>{
 const {state,manager}=fixture(t);const a={id:'abcdef00-1234',source:put(path.join(state.settings.workRoot,'original.pdf')),status:'failed',outputRoot:state.settings.outputRoot,outputDir:path.join(state.settings.outputRoot,'failed_abcdef00')};put(path.join(a.outputDir,'half.json'));state.tasks.push(a);let plan=manager.scan();assert.equal(plan.items.length,1);assert.equal(plan.items[0].safe,false);clean(manager,plan,plan.items);assert.ok(a.resourcesCleaned);assert.ok(fs.existsSync(a.source));
 const b={...a,id:'12345678-1234',resourcesCleaned:null,outputDir:path.join(state.settings.outputRoot,'failed_12345678')};b.source=put(path.join(b.outputDir,'source.pdf'));state.tasks.push(b);assert.equal(manager.scan().items.length,0);
});
test('preview rejects modified files and running jobs, preserves resumed downloads',t=>{const {state,manager,setBusy}=fixture(t);const r=manager.prepare(state.settings,'download');const p=put(path.join(r.temp,'half.bin'));const plan=manager.scan();put(p,'changed after preview');assert.throws(()=>clean(manager,plan),/变化/);setBusy(true);assert.throws(()=>manager.scan(),/运行/);assert.throws(()=>clean(manager,plan),/运行/);assert.ok(fs.existsSync(p));});
test('historical directories remain tracked after setting change and restart',t=>{const {root,state,manager,create}=fixture(t);const r=manager.prepare(state.settings,'convert');put(path.join(r.temp,'page.tmp'));state.settings.workRoot=path.join(root,'new-work');const restarted=create();const p=restarted.scan();assert.ok(p.items.some(i=>i.path===r.temp));clean(restarted,p);assert.ok(!fs.existsSync(r.temp));});
test('successful temp cleanup is scoped, opt-out works, and junction traversal is blocked',t=>{const {root,state,manager}=fixture(t);const r=manager.prepare(state.settings,'convert');put(path.join(r.temp,'scratch'));state.settings.autoCleanTemp=false;manager.finish(r.temp,true);assert.ok(fs.existsSync(r.temp));state.settings.autoCleanTemp=true;manager.finish(r.temp,true);assert.ok(!fs.existsSync(r.temp));const outside=path.join(root,'outside');put(path.join(outside,'keep'));const r2=manager.prepare(state.settings,'convert');fs.symlinkSync(outside,path.join(r2.temp,'junction'),process.platform==='win32'?'junction':'dir');assert.ok(!manager.scan().items.some(i=>i.path===r2.temp));manager.finish(r2.temp,true);assert.ok(fs.existsSync(path.join(outside,'keep')));assert.throws(()=>validateDirectory(path.join(r2.temp,'junction','sub')),/链接|联接/);});
test('reject empty and broad directories, create and verify explicit directory',t=>{const {root}=fixture(t);for(const p of ['',path.parse(root).root,os.homedir()])assert.throws(()=>validateDirectory(p));assert.equal(validateDirectory(path.join(root,'chosen')),path.join(root,'chosen'));});
test('backend stages, download byte counts and indeterminate phases are honest',()=>{
 const p=parseProgress('Processing pages:  45%|████ | 9/20 [00:08<00:10, 1.1it/s]\r');assert.equal(p.percent,45);assert.match(p.detail,/9\/20/);
 const download=parseProgress('weights.safetensors: 12%|▌  | 240M/2.00G [00:03<00:30, 58MB/s]');assert.equal(download.percent,12);assert.match(download.detail,/240M\/2.00G/);
 const phase=parseProgress('Loading model weights',p);assert.equal(phase.percent,null);assert.equal(phase.stage,'加载模型');assert.equal(parseProgress('no numerical progress',phase),phase);
 const reset=parseProgress('OCR-det: 10%| | 1/10 [1it/s]',p);assert.equal(reset.percent,10);assert.equal(reset.stage,'OCR-det');
});
