// Exercise the actual settings click handler; stub only the native directory dialog.
const {app,BrowserWindow,ipcMain}=require('electron');
const fs=require('node:fs');
const path=require('node:path');
const {spawn}=require('node:child_process');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const data=fs.mkdtempSync(path.join(root,'test-output','storage-ui-'));
const chosen=path.join(data,'Chosen model location');
fs.mkdirSync(chosen);
const waste=path.join(data,'work','tmp','convert-fixture');fs.mkdirSync(waste,{recursive:true});fs.writeFileSync(path.join(waste,'scratch.tmp'),'temporary fixture');
fs.writeFileSync(path.join(data,'storage-ledger.json'),JSON.stringify({scopes:[{kind:'temp',path:waste}],history:[]}));
const original=path.join(data,'keep-original.pdf');fs.writeFileSync(original,'original fixture');
let service,win;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<400;i++){const v=await fn();if(v)return v;await delay(80);}throw Error('UI wait timed out');}
ipcMain.handle('pick-directory',()=>chosen);
app.whenReady().then(async()=>{
 service=spawn(process.execPath,[path.join(root,'server.mjs')],{env:{...process.env,ELECTRON_RUN_AS_NODE:'1',MINERU_DESK_DATA:data},windowsHide:true,stdio:'ignore'});
 const connection=await until(()=>{try{return JSON.parse(fs.readFileSync(path.join(data,'connection.json')));}catch{return null;}});
 const api=async(route,body)=>{const r=await fetch(`http://127.0.0.1:${connection.port}/api/${route}`,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+connection.token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return r.json();};
 win=new BrowserWindow({show:false,width:1440,height:930,webPreferences:{preload:path.join(root,'preload.cjs'),sandbox:true,contextIsolation:true,backgroundThrottling:false}});
 await win.loadURL(`http://127.0.0.1:${connection.port}/#token=${connection.token}`);
 await until(()=>win.webContents.executeJavaScript(`!!document.querySelector('[data-action="pick-files"]')`));
 await win.webContents.executeJavaScript(`document.querySelector('[data-nav="settings"]').click()`);
 await until(()=>win.webContents.executeJavaScript(`!!document.querySelector('[data-target="set-modelRoot"]')`));
 await win.webContents.executeJavaScript(`document.querySelector('[data-target="set-modelRoot"]').click()`);
 await until(()=>win.webContents.executeJavaScript(`document.querySelector('#set-modelRoot').value===${JSON.stringify(chosen)}`));
 await delay(250);
 assert.equal((await api('state')).settings.modelRoot,chosen,'Selecting the model directory must persist before downloading; no hidden second Save step');
 await win.webContents.executeJavaScript(`document.querySelector('[data-nav="models"]').click()`);
 await until(()=>win.webContents.executeJavaScript(`!!document.querySelector('[data-action="pick-model-root"]')`));
 assert.ok(await win.webContents.executeJavaScript(`document.querySelector('#main').textContent.includes(${JSON.stringify(chosen)})`));
 await win.webContents.executeJavaScript(`document.querySelector('[data-nav="storage"]').click()`);
 await until(()=>win.webContents.executeJavaScript(`!!document.querySelector('[data-action="storage-scan"]')`));
 await win.webContents.executeJavaScript(`document.querySelector('[data-action="storage-scan"]').click()`);
 await until(()=>win.webContents.executeJavaScript(`!!document.querySelector('[data-cleanup-id]')`));
 await win.webContents.executeJavaScript(`new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))`);
 await delay(350);
 fs.writeFileSync(path.join(data,'storage.png'),(await win.webContents.capturePage()).toPNG());
 await win.webContents.executeJavaScript(`document.querySelector('[data-action="storage-clean"]').click()`);
 await until(()=>win.webContents.executeJavaScript(`document.querySelector('#dialog').open`));
 assert.ok(fs.existsSync(waste),'No deletion before confirmation');
 await win.webContents.executeJavaScript(`document.querySelector('[data-action="dialog-confirm"]').click()`);
 await until(()=>!fs.existsSync(waste));assert.ok(fs.existsSync(original));
 const summary=await api('storage');assert.equal(summary.history.length,1);
 await win.webContents.executeJavaScript(`document.querySelector('[data-nav="hardware"]').click()`);
 await until(()=>win.webContents.executeJavaScript(`!!document.querySelector('[data-action="apply-hardware"]')`));
 await win.webContents.executeJavaScript(`document.querySelector('.hardware-reference').open=true; new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))`);
 await delay(350);
 fs.writeFileSync(path.join(data,'hardware.png'),(await win.webContents.capturePage()).toPNG());
 const dom=await win.webContents.executeJavaScript(`document.querySelector('#main').textContent`);
 assert.match(dom,/Windows Python 3.10–3.12/);assert.match(dom,/OmniDocBench/);
 await win.webContents.executeJavaScript(`document.querySelector('[data-action="apply-hardware"]').click()`);
 await until(()=>win.webContents.executeJavaScript(`!!document.querySelector('[data-action="start"]')`));
 assert.equal((await api('state')).tasks.length,0,'Applying a recommendation never submits or uploads a document');
 console.log('PASS: native folder selection persists, model page path control, scan / confirm / clean API flow, original preserved, cleanup history, hardware detection and apply-without-submitting');
 console.log('Screenshot: '+path.join(data,'storage.png'));
}).then(()=>{service?.kill();win?.destroy();app.exit(0);}).catch(e=>{console.error(e);service?.kill();win?.destroy();app.exit(1);});
