import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {createTaskMaintenance} from '../task-maintenance.mjs';
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'mineru-record-test-'));const settings={outputRoot:path.join(root,'output'),workRoot:path.join(root,'work'),modelRoot:path.join(root,'models')};const state={settings,tasks:[]};let busy=false;const manager=createTaskMaintenance({state,save:()=>{},busy:()=>busy,dataRoot:path.join(root,'data')});function put(p,text='fixture'){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,text);return p;}function task(id='abcdef01-1234'){const x={id,name:'paper.pdf',status:'completed',source:put(path.join(root,id+'.pdf')),outputRoot:settings.outputRoot,outputDir:path.join(settings.outputRoot,'paper_'+id.slice(0,8))};x.markdown=put(path.join(x.outputDir,'paper.md'));put(path.join(x.outputDir,'images/a.png'));state.tasks.push(x);return x;}t.after(()=>{assert.ok(path.basename(root).startsWith('mineru-record-test-'));fs.rmSync(root,{recursive:true,force:true});});return {root,state,manager,put,task,setBusy:v=>busy=v};}
const confirm=(m,p,extra={})=>m.purge({planId:p.planId,confirm:'DELETE_TASK_RESOURCES',...extra});
test('hide preserves queryable records and files; restore reverses it; active tasks refused',t=>{const {manager,task}=fixture(t);const x=task();manager.archive({ids:[x.id]});assert.ok(x.hiddenAt);assert.ok(fs.existsSync(x.markdown));manager.archive({ids:[x.id],restore:true});assert.ok(!x.hiddenAt);x.status='running';assert.throws(()=>manager.archive({ids:[x.id]}),/不能清理/);});
test('purge deletes owned output and edits but preserves original and unrelated models',t=>{const {state,manager,task,put}=fixture(t);const x=task(),model=put(path.join(state.settings.modelRoot,'weight.bin'));put(x.markdown+'.edited.md');const p=manager.preview({ids:[x.id]});assert.equal(p.blocked.length,0);assert.ok(fs.existsSync(x.markdown));const r=confirm(manager,p);assert.equal(r.errors.length,0);assert.equal(state.tasks.length,0);assert.ok(fs.existsSync(x.source));assert.ok(fs.existsSync(model));assert.ok(!fs.existsSync(x.outputDir));});
test('original PDF deletion requires exact paths AND typed second confirmation',t=>{const {manager,task}=fixture(t);const x=task();const p=manager.preview({ids:[x.id],deleteSources:[x.source]});assert.throws(()=>confirm(manager,p),/原始 PDF/);assert.throws(()=>confirm(manager,p,{confirmedSources:[x.source]}),/原始 PDF/);assert.ok(fs.existsSync(x.source));confirm(manager,p,{confirmedSources:[x.source],sourceConfirmation:'删除原始PDF'});assert.ok(!fs.existsSync(x.source));});
test('shared cached result and shared original cannot be removed under another task',t=>{const {state,manager,task}=fixture(t);const x=task();state.tasks.push({...x,id:'bbbbbbbb-1234',status:'reused',reusedFrom:x.id});let p=manager.preview({ids:[x.id],deleteSources:[x.source]});assert.ok(p.blocked.length);assert.throws(()=>confirm(manager,p,{confirmedSources:[x.source],sourceConfirmation:'删除原始PDF'}),/引用|使用/);p=manager.preview({ids:state.tasks.map(t=>t.id)});assert.equal(p.blocked.length,0);confirm(manager,p);assert.ok(fs.existsSync(x.source));});
test('file change, task change, stale plan and busy state invalidate deletion',t=>{const {manager,task,put,setBusy}=fixture(t);const x=task();let p=manager.preview({ids:[x.id]});put(x.markdown,'modified document');assert.throws(()=>confirm(manager,p),/变化/);p=manager.preview({ids:[x.id]});manager.archive({ids:[x.id]});assert.throws(()=>confirm(manager,p),/变化/);p=manager.preview({ids:[x.id]});setBusy(true);assert.throws(()=>confirm(manager,p),/运行/);assert.ok(fs.existsSync(x.markdown));});
test('symlinks, unowned output and original embedded in output are protected',t=>{const {manager,task,put,root}=fixture(t);const x=task();const outside=put(path.join(root,'outside/keep'));fs.symlinkSync(path.dirname(outside),path.join(x.outputDir,'link'),process.platform==='win32'?'junction':'dir');assert.ok(manager.preview({ids:[x.id]}).blocked.length);fs.unlinkSync(path.join(x.outputDir,'link'));x.source=put(path.join(x.outputDir,'original.pdf'));assert.ok(manager.preview({ids:[x.id]}).blocked.length);assert.ok(fs.existsSync(outside));});
