const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bytes=n=>n===null||n===undefined?'未读取':n>=1024**3?(n/1024**3).toFixed(2)+' GB':n>=1024**2?(n/1024**2).toFixed(1)+' MB':Math.ceil(n/1024)+' KB';
export function progressHTML(progress,status){
 const done=['completed','reused'].includes(status),running=status==='running';
 if(!running&&!done)return '';
 const p=done?100:progress?.percent;
 const title=done?(status==='reused'?'已复用现有结果':'已完成'):progress?.stage||'等待进度信息';
 return `<div class="job-progress"><div class="progress-caption"><span>${esc(title)}</span><b>${Number.isFinite(p)?p+'%':'处理中'}</b></div><progress max="100" ${Number.isFinite(p)?`value="${p}"`:''} aria-label="${esc(title)}"></progress>${!done?`<small title="${esc(progress?.detail)}">${esc(progress?.detail||'正在准备，请稍候')}${Number.isFinite(p)?' · 当前文件或阶段的进度':''}</small>`:''}</div>`;
}
export function storageHTML(data,settings){
 const pathFields=[['modelRoot','模型下载目录','Pipeline / VLM 权重、模型库下载片段'],['workRoot','缓存与运行环境目录','转换临时文件、pip 下载缓存、后续安装的 Python 环境'],['outputRoot','默认转换结果目录','Markdown、图片、JSON 与你保存的编辑版本']];
 return `<div class="page-heading"><div><div class="eyebrow">MINERU DESK</div><h1>存储与清理</h1><p class="subtitle">设置文件保存位置，查看磁盘占用，清理下载和转换留下的临时文件。</p></div><button class="button primary" data-action="storage-quick">一键安全清理</button></div>
 <section class="panel panel-body storage-paths"><div class="panel-title"><h2>存储位置</h2><span>选择文件夹后立即保存</span></div>${pathFields.map(([key,title,help])=>`<div class="storage-path-row"><div><b>${title}</b><p class="hint">${help}</p></div><input class="control" id="storage-${key}" value="${esc(settings[key])}" aria-label="${title}"><button class="button small" data-action="storage-folder" data-key="${key}">选择文件夹</button></div>`).join('')}<div class="toolbar"><button class="button soft" data-action="storage-save">保存路径</button><span class="hint">建议选择 D / E 盘的专用子文件夹。</span></div><p class="hint storage-warning">新路径用于之后提交的任务，已排队的任务仍使用原路径。已有文件不会搬迁或删除；旧缓存也可以在下方扫描。</p></section>
 <div class="storage-locations">${data.locations.map(l=>`<section class="panel panel-body"><b>${esc(l.label)}</b><div class="storage-number">${bytes(l.bytes)}</div><p class="storage-location" title="${esc(l.path)}">${esc(l.path)}</p><div class="disk-meter"><span style="width:${l.total?Math.min(100,100*(l.total-l.free)/l.total):0}%"></span></div><small>所在磁盘可用 ${bytes(l.free)} / 总容量 ${bytes(l.total)}</small>${l.error?`<p class="hint">${esc(l.error)}</p>`:''}<button class="text-link" data-action="storage-open" data-path="${esc(l.path)}">打开目录 ↗</button></section>`).join('')}</div>
 <section class="panel panel-body storage-policy"><h2>自动清理与空间预留</h2><label class="check-row">成功后自动清理本次任务的临时文件<input type="checkbox" id="storage-auto" ${settings.autoCleanTemp?'checked':''}></label><label class="field-label" for="storage-min-free">开始任务前，磁盘至少保留（GB）</label><div class="toolbar"><input class="control" id="storage-min-free" type="number" min="0.25" max="100" step="0.25" value="${settings.minFreeGB}"><button class="button" data-action="storage-policy">保存设置</button></div><p class="hint">开始任务前会检查剩余空间，但不会估算本次任务需要多少空间。直接用其他程序下载的文件不在清理范围内。</p></section>
 <section class="panel panel-body"><div class="panel-title"><h2>可清理资源</h2><button class="button" data-action="storage-scan">扫描 / 刷新占用</button></div><p class="hint">${data.busy?'当前有转换、下载或服务运行；停止后才能清理。':'默认勾选：临时残留、未完成下载片段、安装下载缓存。'} 不会清理原始文档、已关联模型，以及正常转换结果中的图片和编辑文件。</p>
 ${data.items?`<div class="cleanup-summary">安全清理预计释放 <b>${bytes(data.safeBytes)}</b> <span> ${data.items.length} 项</span></div><div class="cleanup-list">${data.items.length?data.items.map(i=>`<label class="cleanup-row"><input type="checkbox" data-cleanup-id="${i.id}" ${i.safe?'checked':''}><div><b>${esc(i.label)}</b><span class="${i.safe?'':'manual-label'}">${i.safe?'可重建':'需单独确认'}</span><small>${esc(i.path)}</small></div><strong>${bytes(i.bytes)}</strong></label>`).join(''):'<p class="empty">没有找到可清理的临时文件。</p>'}</div><button class="button danger" data-action="storage-clean" ${data.items.length?'':'disabled'}>清理选中项</button>`:'<div class="empty">点击“扫描”，查看哪些文件可以清理。</div>'}
 <p class="hint">不会扫描整个系统 Temp 或其他应用的全局缓存。清理会永久删除所选项；未完成模型片段被删除后，需要重新下载相应部分。</p></section>
 <section class="panel panel-body storage-history"><h2>最近清理记录</h2>${data.history.length?data.history.map(r=>`<details><summary>${esc(new Date(r.at).toLocaleString())} · 释放 ${bytes(r.bytes)} · ${r.removed.length} 项${r.errors.length?' · 部分失败':''}</summary><pre>${esc(r.removed.map(x=>x.path).join('\n'))}</pre>${r.errors.map(e=>`<p>${esc(e.path)}：${esc(e.error)}</p>`).join('')}</details>`).join(''):'<p class="hint">还没有清理记录。</p>'}</section>`;
}
